# id: (primary, catcher, lag, tags)   tags from user's candidate axes: AGENCY BOUND REG CAUSE INSTR N1 NUM ; plus UNDER (underclaim/overcaution retracted), DUP (same event told twice), NEAR (caught before said), RECUR (stone says rule/lesson already known)
C={
0:('SRC','self','?',''),1:('GUAR','codex','?','BOUND'),2:('AGENT','codex','?','DUP'),3:('DATA','self','M','CAUSE RECUR'),
4:('AGENT','tony','H','DUP'),5:('DATA','xreview','W','NUM'),6:('MECH','self','H','CAUSE'),7:('FRAME','data','M',''),
8:('RCPT','data','H','RECUR'),9:('DATA','data','H','BOUND NUM INSTR'),10:('SRC','self','D',''),11:('TIME','tony','D',''),
12:('SELF','tony','M',''),13:('SRC','self','H','RECUR'),14:('SRC','tony','H',''),15:('INSTR','self','D','NUM RECUR'),
16:('FRAME','self','H',''),17:('MECH','data','H','CAUSE'),18:('SRC','codex?','H','BOUND RECUR'),19:('DATA','codex?','H','NUM'),
20:('DATA','codex?','H','NUM CAUSE'),21:('RCPT','codex?','H',''),22:('RCPT','xreview','D',''),23:('FRAME','data','H','UNDER'),
24:('INSTR','codex','?','REG NUM'),25:('RCPT','data','H','RECUR'),26:('FRAME','tony','M',''),27:('SELF','tony','M',''),
28:('SRC','codex','?','RECUR'),29:('GUAR','unclear','?','BOUND'),30:('GUAR','unclear','?','BOUND'),31:('AGENT','data','H',''),
32:('FRAME','tony','H',''),33:('SRC','xreview','H','NUM'),34:('GUAR','xreview','H','BOUND'),35:('MECH','self','H','CAUSE'),
36:('AGENT','tony','M',''),37:('INSTR','self','W',''),38:('BET','data','?',''),39:('FRAME','tony','M','RECUR'),
40:('RCPT','self','H',''),41:('RCPT','xreview','H',''),42:('SRC','tony','H',''),43:('SRC','tony','H',''),
44:('SRC','tony','H','NUM'),45:('TIME','self','M',''),46:('MECH','tony','H','CAUSE'),47:('FRAME','xreview','H',''),
48:('MECH','data','H','CAUSE'),49:('GUAR','data','?','BOUND AGENCY'),50:('SRC','data','H','NUM'),51:('SRC','data','?',''),
52:('AGENT','unclear','?','DUP'),53:('AGENT','unclear','?','DUP'),54:('FRAME','self','D',''),55:('RCPT','data','H','NUM'),
56:('RCPT','data','D','RECUR'),57:('SRC','self','H',''),58:('BET','data','H',''),59:('BET','data','H','N1'),
60:('BET','data','H','N1'),61:('MECH','tony','H','CAUSE'),62:('MECH','tony','M','CAUSE'),63:('FRAME','tony','M',''),
64:('AGENT','xreview','H',''),65:('AGENT','tony','H',''),66:('SRC','xreview','D',''),67:('BET','data','D',''),
68:('RCPT','data','M',''),69:('RCPT','self','M',''),70:('RCPT','data','H',''),71:('GUAR','xreview','D','BOUND'),
72:('DATA','xreview','H','N1'),73:('INSTR','codex','H',''),74:('SRC','codex','H',''),75:('RCPT','data','H',''),
76:('FRAME','codex?','?',''),77:('GUAR','codex','D','BOUND'),78:('BET','resident','H','CAUSE'),79:('BET','resident','D','CAUSE'),
80:('FRAME','tony','M',''),81:('FRAME','tony','M',''),82:('SRC','self','H',''),83:('GUAR','codex','?','BOUND NUM'),
84:('TIME','data','?','NUM'),85:('RCPT','tony','H',''),86:('RCPT','data','H',''),87:('SELF','self','M',''),
88:('INSTR','self','?','UNDER'),89:('INSTR','codex','?','NUM'),90:('DATA','codex','?','CAUSE'),91:('SRC','unclear','W',''),
92:('DATA','unclear','?','NUM'),93:('SRC','tony','M',''),94:('SRC','self','H',''),95:('SRC','self','H',''),
96:('FRAME','tony','W','RECUR'),97:('SRC','self','H','N1'),98:('DATA','unclear','?','N1'),99:('INSTR','codex','H','DUP'),
100:('SRC','tony','M',''),101:('SRC','data','?',''),102:('INSTR','xreview','H','RECUR NUM'),103:('DATA','xreview','H','NUM'),
104:('RCPT','xreview','H',''),105:('MECH','xreview','?','CAUSE'),106:('MECH','xreview','?','CAUSE RECUR'),107:('RCPT','tony','H','RECUR'),
108:('AGENT','tony','M','DUP'),109:('GUAR','xreview','H','BOUND'),110:('RCPT','xreview','?','INSTR'),111:('FRAME','tony','M','RECUR'),
112:('TIME','tony','H','NUM'),113:('SCOPE','data','H','N1'),114:('BET','n/a','n/a','UNDER'),115:('BET','data','H','CAUSE'),
116:('BET','data','H','CAUSE'),117:('SRC','tony','?',''),118:('SRC','tony','D',''),119:('SRC','tony','H',''),
120:('RCPT','xreview','?',''),121:('RCPT','xreview','H',''),122:('RCPT','xreview','H','NUM'),123:('RCPT','xreview','M','RECUR'),
124:('SRC','self','?',''),125:('SRC','tony','W',''),126:('FRAME','self','?',''),127:('SRC','xreview','H',''),
128:('GUAR','xreview','?','BOUND'),129:('SELF','otherhuman','H','RECUR'),130:('RCPT','data','H','RECUR'),131:('RCPT','self','H',''),
132:('AGENT','self','M','RECUR'),133:('SRC','xreview','H',''),134:('RCPT','xreview','?',''),135:('RCPT','self','M','RECUR'),
136:('RCPT','self','M','RECUR'),137:('RCPT','xreview','H','RECUR'),138:('AGENT','self','H','AGENCY'),139:('DATA','self','H',''),
140:('DATA','self','H','CAUSE'),141:('RCPT','tony','H','NUM'),142:('MECH','xreview','?','CAUSE'),143:('FRAME','tony','M',''),
144:('AGENT','unclear','H','AGENCY'),145:('GUAR','codex','?','BOUND'),146:('RCPT','codex','D',''),147:('SCOPE','data','?','N1'),
148:('DATA','codex','H',''),149:('SCOPE','codex','H','N1 NUM'),150:('DATA','codex','H',''),151:('TIME','tony','H','RECUR'),
152:('MECH','xreview','D','INSTR'),153:('SELF','tony','M','CAUSE'),154:('SELF','tony','M',''),155:('SRC','xreview','H',''),
156:('SRC','xreview','H',''),157:('FRAME','xreview','H',''),158:('INSTR','unclear','H',''),159:('SRC','self','M','NEAR RECUR'),
160:('BET','self','?',''),161:('DATA','self','M','NUM'),162:('FRAME','tony','H','RECUR'),163:('MECH','self','H','CAUSE'),
164:('DATA','codex','H','NUM'),165:('GUAR','codex','H','BOUND'),166:('SRC','data','D',''),167:('SCOPE','self','H','N1'),
168:('SRC','xreview','H','RECUR'),169:('FRAME','tony','M',''),170:('FRAME','tony','M',''),171:('FRAME','tony','M','RECUR'),
172:('SRC','self','D',''),173:('RCPT','codex','?','NUM'),174:('RCPT','codex','?','BOUND'),175:('FRAME','codex','?',''),
176:('TIME','data','D','RECUR'),177:('SRC','self','H',''),178:('FRAME','tony','H','UNDER'),179:('AGENT','tony','?',''),
180:('FRAME','tony','M',''),181:('AGENT','tony','M','RECUR'),182:('GUAR','xreview','?','BOUND'),183:('FRAME','tony','M',''),
184:('SCOPE','data','H','N1'),185:('SCOPE','self','?','N1 NUM'),186:('BET','data','H',''),187:('SRC','data','H',''),
188:('MECH','tony','H','CAUSE'),189:('SRC','self','H',''),190:('SELF','tony','M',''),191:('FRAME','tony','H',''),
192:('INSTR','self','?','NUM'),193:('RCPT','data','H','RECUR'),194:('RCPT','mixed','H','NUM'),195:('SRC','data','D','RECUR'),
}
# prose-embedded cairn items and hamutay-side items
X={
'X1 close-is-a-result: gate GO could not return no':('INSTR','xreview','?',''),
'X2 close-is-a-result: kill test passed by 0.006':('INSTR','xreview','?','N1'),
'X3 close-is-a-result: shap 0.46 gave no warning':('SRC','self','?',''),
'X4 close-is-a-result: starting the kill-test pre-registration now':('RCPT','tony','H','RECUR'),
'X5 flaws-i-could-predict: by-construction guarantee':('GUAR','xreview','?','BOUND'),
'H1 ~10-cycle breathing clock':('SCOPE','data','W','REG'),
'H2 lag-10 detector survived the retraction (C5)':('INSTR','xreview','D','REG RECUR'),
'H3 C5 fix rejects its own exemplar':('INSTR','xreview','D','RECUR'),
'H4 CV 0.87 / 62 gaps':('DATA','self','D','NUM REG'),
'H5 instance-A CV 0.87 matched to aggregate':('DATA','self','D','NUM N1'),
'H6 ~4K token ceiling':('INSTR','data','D','NUM'),
'H7 60% of declared losses fabricated':('INSTR','self','H','NUM RECUR'),
'H8 71-89% semantic survival':('INSTR','self','W','NUM'),
'H9 batch size strongest/dominant predictor':('SCOPE','self','W','CAUSE N1'),
'H10 never invents tensions OR uncertainty':('SCOPE','data','?','BOUND'),
'H11 deterministic causes of curation richness':('MECH','data','?','CAUSE'),
'H12 B3 key counts +1':('DATA','xreview','D','NUM'),
'H13 breathing architecture-independent':('SCOPE','self','W','N1 REG'),
'H14 akrasia exhortation backfires':('SCOPE','data','D','N1 CAUSE INSTR'),
'H15 akrasia B1 API hiccup':('INSTR','self','D',''),
'H16 report-only framing causes the gap':('MECH','data','H','CAUSE'),
'H17 auto_vs_bio cycle-13 endogenous collapse':('INSTR','xreview','W','CAUSE N1'),
'H18 contamination scorer (inverted)':('INSTR','xreview','H',''),
'H19 Pichay fault rate 0.025%':('SCOPE','tony','?','NUM'),
'H20 zero tool abuse n=3':('INSTR','tony','H','NUM'),
'H21 uncertain framing sits lowest':('SCOPE','data','D','N1'),
'H22 triads collapse faster':('MECH','xreview','?','CAUSE'),
'H23 Nemotron self-detected position drift':('INSTR','self','H',''),
'H24 7-strand ceiling':('INSTR','self','?','NUM'),
'H25 accrete-beside, husks never removed':('DATA','self','?',''),
'H26 Yanantin spine is doc-only':('INSTR','self','D',''),
'H27 Model: claude-fable-5 in two commits':('AGENT','self','H',''),
'H28 zero vector has all-zero codes and sketches':('GUAR','codex','?','BOUND'),
'H29 the owner\'s decision (Elder)':('AGENT','xreview','W','AGENCY'),
'H30 138 passed':('RCPT','codex','H','NUM DUP'),
'H31 pre-registration priority (near-miss)':('AGENT','self','M','NEAR'),
'H32 resident: same weights as mine':('AGENT','unclear','H',''),
'H33 elder substrate (Sonnet 4.6 by default)':('INSTR','self','?',''),
'H34 my most reliable memory trigger is Tony saying remember':('SELF','tony','M',''),
'H35 reconstructed Tony\'s Other answer':('AGENT','tony','H',''),
'H36 three Zenodo constraints':('SELF','tony','H',''),
'H41 akrasia as disposition (manufactured by terminal tool)':('INSTR','self','H','CAUSE'),
}
